version: '2'
services:
  loadbalancer:
    image: "threethink/shit-city-loadbalancer:${TAG}"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/traefik:/tmp/"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lb"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:lb.turds.dog"
      - "traefik.frontend.passHostHeader=true"
    networks:
      - production
    restart: always
networks:
  production:
    external: true
