version: '2'
services:
  loadbalancer:
    image: "threethink/shit-city-loadbalancer:e63043b98d1d65db16029c5a22523125682ca216"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/traefik:/tmp/"
    labels:
      - "traefik.backend=lb"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:lb.andimenge.de"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.auth.basic=ops:$$apr1$$Pi7zGg1E$$UkbSPqeVClc0DaEAgQ3i0/" #escape single $ with $$
    networks:
      - production
    restart: always
networks:
  production:
    external: true
