# Global Configuration
checkNewVersion = false
defaultEntryPoints = ["http", "https"]

# EntryPoints
[entryPoints]
  # HTTP
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # HTTPS
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

# Lets Encrypt Config
[acme]
email = "foo.bar@lol.com"
storage = "/tmp/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
  entryPoint = "http"
  
# Traefik Web UI
[web]
address = ":8080"
ReadOnly = true

# Docker Conf
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
