# Global Configuration
checkNewVersion = false
defaultEntryPoints = ["http", "https"]

[accessLog]

# EntryPoints
[entryPoints]
  # HTTP
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    permanent = true
    entryPoint = "https"
  # HTTPS
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

  # WEB UI (API)
  [entryPoints.api]
    address=":8080"
    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
        users = [
          "ops:$apr1$Pi7zGg1E$UkbSPqeVClc0DaEAgQ3i0/"
        ]

# Lets Encrypt Config
[acme]
email = "foo.bar@lol.com"
storage = "/tmp/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
  entryPoint = "http"

# Activate API and Dashboard
[api]
  entryPoint = "api"
  dashboard = true
[api.statistics]
  # Number of recent errors logged.
  #
  # Default: 10
  #
  recentErrors = 10

# Docker Conf
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
# Expose services by default in Traefik.
exposedbydefault = false
